### ISSUE TITLE
Doesn't work with Jest 27

### ISSUE THREAD

**Issue by gustavohenke** [asvetliakov/jest-create-mock-instance#26]
Looks like Jest 27 introduced a breaking change to `jest-mock` -- it no longer exports a global instance of `ModuleMocker`: facebook/jest#10887

I think fixing jest-create-mock-instance to work with both Jest <27 and 27+ should be reasonably simple, so I'll submit a PR if that's okay 😃

**Comment by dayemsiddiqui** [comment]
@gustavohenke hi did you manage some time to create a PR for this :). This is a really useful library and I used in my past projects and its a pity that I cant use it in my new projects, I am thinking for forking this repo and upgrading it to support newer versions

**Comment by dayemsiddiqui** [comment]
Also I think it would be really nice if jest could provide this method directly out of the box. I think its really useful

**Comment by dayemsiddiqui** [comment]
It turns out jest is now offering a separate package for module mocker: https://www.npmjs.com/package/jest-mock

**Comment by extravio** [comment]
> It turns out jest is now offering a separate package for module mocker: https://www.npmjs.com/package/jest-mock

Can the documentation be updated? I don't understand how to use the "ModuleMocker".

**Comment by Bil0** [comment]
Hello, 
@gustavohenke can you please provide the fix or a workaround to work with Jest 27+ ?

**Comment by gustavohenke** [comment]
There you go, Jest 27 support in PR #27! 😄

**Comment by ChrisDoernen** [comment]
@gustavohenke nice! Would love to see a new release...

**Comment by ChrisDoernen** [comment]
For anyone following, a temporary package including the PR was released by @darraghoriordan (awesome, thanks): [https://www.npmjs.com/package/@darraghor/jest-create-mock-instance](https://www.npmjs.com/package/@darraghor/jest-create-mock-instance)

Alternatively there is the option to use [patch-package](https://www.npmjs.com/package/patch-package) and apply the patch from the PR manually.

@asvetliakov can you please review, merge an publish?

**Comment by asvetliakov** [comment]
Published 2.0 with PR merged 😅
