### ISSUE TITLE
Not compatible with jest 24.5.0

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [asvetliakov/jest-create-mock-instance#5]
I have upgraded project to 
"jest": "^24.5.0" and "@types/jest": "^23.3.3",
and started receiving errors on `mockReturnValue`

```
 loggerService = createMockInstance(RemoteLogger);
 loggerService.log.mockReturnValue(new Subject());
```

`Argumen type is not assignable to type....` which, i think, means interfaces are not up to date.
Also upgrading to latest 1.1 package version brings another error when doing `createMockInstance(ComponentFactoryResolver);` with similar error

**Comment by asvetliakov** [comment]
#27
